name: Trigger API on README change

on:
  push:
    paths:
      - 'README.md'

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Call API
      run: |
        curl -X GET "https://count-viewer.vercel.app/api/action/github" \
          -H "Referer: https://github.com/${{ github.repository }}"
